version: "3"
services:
  mongo:
    image: mongo
    container_name: dragons_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./backend/.env
    depends_on:
      - mongo


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    command: npm run dev
  
  admin-runner:
    build:
      context: ./backend
    command: node createAdmin.js
    depends_on:
      - mongo
    networks:
      - default

volumes:
  mongodb_data:
