version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
      build: ./backend
      container_name: backend-app
      restart: unless-stopped
      ports:
        - "4000:5000"
      environment:
        - MONGO_URI=mongodb://mongo:27017/cyberdragons
        - PORT=4000
      depends_on:
        - mongo
      volumes:
        - ./backend:/app
      command: npm start
  mongo:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
